version: '3'

services:
  mysql:
    image: mysql:5.7.18
    environment:
      MYSQL_ROOT_PASSWORD: 'very-secret-assignment-password'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html/app
      - /var/www/html/app/vendor
      - /var/www/html/app/var
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/var/www/html/app
      - /var/www/html/app/vendor
      - /var/www/html/app/var
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysqldata: {}
